// Mock events data
export const mockEvents = [
  {
    _id: "event_1",
    title: "Tech Innovation Summit 2024",
    description: "<p>Join us for the biggest technology innovation summit of the year featuring keynote speakers, workshops, and networking opportunities.</p>",
    slug: "tech-innovation-summit-2024",
    status: "published",
    current_attendees: 150,
    max_attendees: 500,
    registration_deadline: "2024-12-20T23:59:59Z",
    startAt: "2024-12-25T09:00:00Z",
    endAt: "2024-12-25T17:00:00Z",
    venue: {
      type: "physical",
      address: "Convention Center",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      postal_code: "94105",
    },
    ticketPrice: 299,
    currency: "USD",
    isPaidEvent: true,
    is_public: true,
    createdAt: "2024-11-01T10:00:00Z",
    updatedAt: "2024-12-01T15:30:00Z",
    orgn_user: {
      _id: "org_1",
      name: "TechCorp Solutions",
    },
  },
  {
    _id: "event_2",
    title: "AI & Machine Learning Workshop",
    description: "<p>Hands-on workshop covering the latest trends in artificial intelligence and machine learning technologies.</p>",
    slug: "ai-ml-workshop",
    status: "published",
    current_attendees: 75,
    max_attendees: 100,
    registration_deadline: "2024-12-15T23:59:59Z",
    startAt: "2024-12-18T14:00:00Z",
    endAt: "2024-12-18T18:00:00Z",
    venue: {
      type: "virtual",
      platform: "Zoom",
      virtual_link: "https://zoom.us/j/1234567890",
    },
    ticketPrice: 0,
    currency: "USD",
    isPaidEvent: false,
    is_public: true,
    createdAt: "2024-10-15T12:00:00Z",
    updatedAt: "2024-11-20T09:45:00Z",
    orgn_user: {
      _id: "org_2",
      name: "Innovation Labs",
    },
  },
  {
    _id: "event_3",
    title: "Digital Marketing Masterclass",
    description: "<p>Comprehensive masterclass on digital marketing strategies, SEO optimization, and social media marketing.</p>",
    slug: "digital-marketing-masterclass",
    status: "draft",
    current_attendees: 0,
    max_attendees: 200,
    registration_deadline: "2025-01-10T23:59:59Z",
    startAt: "2025-01-15T10:00:00Z",
    endAt: "2025-01-15T16:00:00Z",
    venue: {
      type: "hybrid",
      address: "Marketing Hub",
      city: "New York",
      state: "NY",
      country: "USA",
      postal_code: "10001",
      platform: "Microsoft Teams",
      virtual_link: "https://teams.microsoft.com/l/meetup-join/...",
    },
    ticketPrice: 149,
    currency: "USD",
    isPaidEvent: true,
    is_public: false,
    createdAt: "2024-11-25T14:30:00Z",
    updatedAt: "2024-12-01T11:15:00Z",
    orgn_user: {
      _id: "org_3",
      name: "Digital Marketing Pro",
    },
  },
];
